config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'

  get 'contacts/create'

  get 'contacts/thanks'

  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'
  get 'static_pages/home'
  get '/help', to:'contacts#new'
  get '/about', to:'static_pages#about'
  get '/contact', to:'static_pages#contact'
  get '/video_requirements', to:'static_pages#video_requirements' 
  
  resources :microposts

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :contacts
  resources :account_activations, only: [:edit]
  resources :password_resets, only:[:new, :create, :edit, :update]
  resources :microposts, only:[:create, :destroy]
end 

app/models/micropost.rb
class Micropost < ApplicationRecord
    belongs_to :user 
    default_scope->{ order(created_at: :desc)}
    mount_uploader :video, VideoUploader
    validates :user_id, presence: true
    validates :content, length: {maximum:140}, presence: true 
    validate :video_size 
    
    private 
    
    # validates the size on an uploaded video
    def video_size
        if video.size > 25.megabytes
           errors.add(:video, "should be less than 25MB") 
        end
    end
    
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
    before_action :logged_in_user, only:[:index, :create, :destroy]
    before_action :correct_user, only: :destroy
    before_action :admin_user, only: [:index, :destroy ]  
    
    def index
        @microposts = Micropost.all
    end
    
    def create
        @micropost = current_user.microposts.build(micropost_params)
        if @micropost.save
           flash[:success]  = "Post created!"
           redirect_to root_url
        else
            @feed_items = []
            render 'static_pages/home'   
        end
    end
    
    def destroy
        @micropost.destroy
        flash[:success] = "Micropost deleted"
        redirect_to request.referrer || root_url
    end
    
    private 
        
        def micropost_params
           params.require(:micropost).permit(:content, :video)
        end
        
        def correct_user
            @micropost = current_user.microposts.find_by(id: params[:id])
            redirect_to root_url if @micropost.nil?
        end
        
        def admin_user
            redirect_to(root_url)  unless current_user.admin?
        end
        
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_form.html.erb
<%= form_for(micropost) do |f| %>
  <% if micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% micropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
    <span class="content">
        <%= video_tag micropost.video.url, height:"100px" if micropost.video? %>
        <%= micropost.content %>
    </span>
    <span class="timestamp">
        Posted <%= time_ago_in_words(micropost.created_at)%> ago.
    </span>
    <!--- <%= link_to "delete", micropost, method: :delete, data: {confirm:"You sure?"} %> -->
</li>

app/views/microposts/edit.html.erb
<h1>Editing Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Video</th>
      <th>Content</th>
      <th>Name</th>
      <th>Email</th>
      <th>Date</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |micropost| %>
      <tr>
        <td><%= video_tag micropost.video.url, height:"100px" if micropost.video? %></td>
        <td><%= micropost.content %></td>
        <td><%= micropost.user.name %></td>
        <td><%= micropost.user.email %></td>
        <td><%= micropost.created_at.strftime('%F') %></td>
        <td><%= micropost.created_at.strftime('%T') %></td>
        <td><%= link_to 'Show', micropost %></td>
        <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
        <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<h1>New Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @micropost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @micropost.user_id %>
</p>

<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>