config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'

  get 'contacts/create'

  get 'contacts/thanks'

  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'
  get 'static_pages/home'
  get '/help', to:'contacts#new'
  get '/about', to:'static_pages#about'
  get '/contact', to:'static_pages#contact'
  get '/video_requirements', to:'static_pages#video_requirements' 
  
  resources :microposts

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :contacts
  resources :account_activations, only: [:edit]
  resources :password_resets, only:[:new, :create, :edit, :update]
  resources :microposts, only:[:create, :destroy]
end 

app/views/layouts/_footer.html.erb
<footer>
    <nav>
        <!-- remove fooder use as placeholder 
        <ul class="footer-nav">
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
        </ul>
        -->
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
    <!-- <a class="logo" href="/"><%= image_tag "logo.png", height: "43px" %></a> -->
    <ul class="main-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <li><%= link_to "Official Rules", about_path %></li>
        <li><%= link_to "Video Requirements", video_requirements_path %></li>        
        
    </ul>
    <ul class="right-nav">
        <% if logged_in? %>
            <li><%= link_to "Log out", logout_path, method:"delete"%></li>
        <% else %>
            <li><%= link_to "Log in", login_path %></li>
        <% end %>
    </ul>
    <div class="hamburger-menu">
        <%= image_tag "hamburger-menu.png", size: "24x24", id: "menu-mobile--button" %>
    </div>
    
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link href="https://fonts.googleapis.com/css?family=Fjalla+One|Magra|Saira+Extra+Condensed:400,700|Staatliches&display=swap" rel="stylesheet">

  </head>
  <body>

    <div class="mobile-nav" id="menu-mobile--dropdown" style="display: none;">
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>        
        <% if logged_in? %>
            <li><%= link_to "Log out", logout_path, method:"delete"%></li>
        <% else %>
            <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </div>
    <main>
      <%= render 'layouts/header' %>
      <section id="hero">
        <div class="container">
          <div class="hero-text">
            <h1 class="heading">living the moment</h1>
            <!-- <div class="separator left"></div> -->
            <h2 class="subheading">Video Competition</h2>
            <!-- <div class="separator right"></div> -->
          </div>
        </div>
      </section>
      <section id="content" style="margin-bottom: 10em;">
        <div class="container">
          <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>
          <%= yield %>
        </div>
      </section>
      <section id="footer">
        <div class="container">
          <%= render 'layouts/footer' %>
        </div>
      </section>
    </main>
  </body>
</html>


<script type="text/javascript">
  
var mobileMenuButton    = $('#menu-mobile--button'),
    mobileMenuDropdown  = $('#menu-mobile--dropdown');

  $('.hamburger-menu').click(function() {
    event.stopPropagation();  

    $(mobileMenuDropdown).css('display') == 'none' ? mobileMenuDropdown.show() : mobileMenuDropdown.hide();
/*
    if ($('main').hasClass('active')) {
      $('main').removeClass('active');
    } else {
      $('main').addClass('active');
    }
*/  
  });
  
  $('main').click(function() {
    // $('main').removeClass('active');
    mobileMenuDropdown.hide();
  });
  
</script>